services:
  - type: web
    name: youtube-clone-invidious
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    domains:
      - youtube-clone-invidious.onrender.com